name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@main

      - name: Configlet Linter
        run: configlet lint --track-id pharo .
    
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Fetch smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@d14216202879c4ed2ff5a0852face85af3a77ce4
        id: smalltalkci
        with: 
          smalltalk-version: 'Pharo64-8.0'
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15
        
  tree:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch configlet
        uses: exercism/github-actions/configlet-ci@main

      - name: Configlet Tree
        run: configlet tree --with-difficulty .
